service: pokemon

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  lambdaHashingVersion: "20201221"
  environment:
    ENV: lambda
    TWITTER_API_KEY: ${env:TWITTER_API_KEY}
    TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}
    SECRET: ${env:SECRET}
    BOT_TWITTER_CONSUMER_KEY: ${env:BOT_TWITTER_CONSUMER_KEY}
    BOT_TWITTER_CONSUMER_SECRET: ${env:BOT_TWITTER_CONSUMER_SECRET}
    BOT_TWITTER_TOKEN: ${env:BOT_TWITTER_TOKEN}
    BOT_TWITTER_SECRET: ${env:BOT_TWITTER_SECRET}
    POKEDOGE_BOT_TWITTER_TOKEN: ${env:POKEDOGE_BOT_TWITTER_TOKEN}
    POKEDOGE_BOT_TWITTER_SECRET: ${env:POKEDOGE_BOT_TWITTER_SECRET}
    TWITTER_CALLBACK_URL: ${env:TWITTER_CALLBACK_URL}
functions:
  dollarJob:
    handler: app/app.dollarJob
    events:
    - schedule:
        rate: cron(5,35 9-18 ? * 1-5 *)
  dogeJob:
    handler: app/app.dogeJob
    events:
    - schedule:
        rate: cron(0 10 * * ? *)
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true